export const selectOptions = [
  { label: 'React', value: 1 },
  { label: 'Next.js', value: 2 },
  { label: 'Redux Toolkit', value: 3 },
  { label: 'Sass', value: 4 },
  { label: 'React-router', value: 5 },
  { label: 'Vite', value: 6 },
  { label: 'Zustand ', value: 7 },
  { label: 'TanStack Query', value: 8 },
  { label: 'React-hook-form', value: 9 },
  { label: 'Framer-motion', value: 10 },
  { label: 'TypeScript', value: 11 },
  { label: 'Firebase', value: 12 },
  { label: 'Gulp', value: 13 },
  { label: 'Angular', value: 14 },
]
